dist: trusty

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - LINT="yes"
  - DJANGO="1.9"
  - DJANGO="1.10"
  - DJANGO="1.11"

matrix:
  exclude:
  - python: "3.4"
    env: LINT="yes"
  - python: "3.5"
    env: LINT="yes"
  - python: "3.6"
    env: LINT="yes"
  - python: "3.6"
    env: DJANGO="1.9"
  - python: "3.6"
    env: DJANGO="1.10"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - pip install tox tox-travis codecov

# command to run tests, e.g. python setup.py test
script:
  - tox

after_success:
  - codecov
