# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

sudo: false

matrix:
  include:
    - python: 2.7
      env:
        - TOX_ENV=py2.7
    - python: 2.7
      env:
        - TOX_ENV=docs
    - python: 3.4
      env:
        - TOX_ENV=py3.4
    - python: 3.5
      env:
        - TOX_ENV=py3.5


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - pip install tox
  - pip install codecov

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV

after_success:
  - codecov

notifications:
  email: false
